### ISSUE TITLE
Add ability to lock body scroll when offcanvas is open

### ISSUE THREAD

**Issue by neosiae** [neosiae/react-aria-offcanvas#4]
- This should be a prop so users can choose whether or not to use it.
- Should be cross-browser compatible.
- Maybe [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock)?
- Write a proper test.

**Comment by koolamusic** [comment]
I am able to override this behaviour using `		document.querySelector('html').style.overflow = 'hidden'
` on ComponentDidMount of my Mobile Menu Navigation, not sure about much browser compatibility, but works on Safari and chrome both on ios and android and on desktop devices as well

**Comment by neosiae** [comment]
Would you like to send PR?

**Comment by koolamusic** [comment]
alright, will look at doing that

**Comment by neosiae** [comment]
@koolamusic What is going on here?

**Comment by koolamusic** [comment]
What's the ETA

**Comment by neosiae** [comment]
Take your time now, do it when you come home. :)

**Comment by neosiae** [comment]
@koolamusic what is happening here?

**Comment by koolamusic** [comment]
Hello @neosiae took a break, I will implement this this week, thanks a lot for the patience

**Comment by jokokoloko** [comment]
@neosiae @koolamusic the `style="overflow: hidden;"` does not seem to be cleared when the offcanvas is closed which keeps the body unscrollable.

**Comment by koolamusic** [comment]
Just ran a test, for some odd reason can't replicate this on my end. Could you please provide more information to help debug this

**Comment by jokokoloko** [comment]
Go here https://admiring-benz-05506b.netlify.com/catalog and view it in a mobile viewport (notice that you can scroll up and down this page) so that the hamburger toggle button appears. Press the hamburger toggle button to open the offcanvas and to apply the scroll lock style. Close the offcanvas by click into the "greyed out" area and notice that the scroll lock style remains.

**Comment by neosiae** [comment]
Could you share your code?

**Comment by jokokoloko** [comment]
@neosiae @koolamusic here: https://github.com/jokokoloko/scroll-locked

**Comment by neosiae** [comment]
@jokokoloko Please update to the latest version and let me know if the problem is still there.

**Comment by jokokoloko** [comment]
Functionally it works and there is no longer a problem, thanks! But why add `style="overflow-x: hidden; overflow-y: inherit;"` rather than completely clearing the style?

**Comment by jokokoloko** [comment]
@neosiae @koolamusic when changing to another route while the offcanvas is open the body still remains scroll-locked so, clicking on a link within the offcanvas will direct to a page that is scroll-locked.

**Comment by koolamusic** [comment]
@jokokoloko you propose that clearing the style should make things better.

**Comment by neosiae** [comment]
Could you share a link so we can see it?

**Comment by jokokoloko** [comment]
@neosiae here: https://admiring-benz-05506b.netlify.com/

Shrink your browser width to mobile phone size, click on the top left "hamburger" button to open the offcanvas, click on "Our Health Tests" to expand the dropdown, click on any of the links within such as "Hormone Testing", and then once directed to the new page attempt to scroll. You shouldn't be able to scroll and if you check the body tag in inspector the style with "overflow: hidden" is present. Refresh the page and you should now be able to scroll as expected.

@koolamusic either when a route changes the scroll-locking style should be cleared or when the offcanvas is closed the style should be cleared, not via a toggle. Doing both of these would be good as well.

This site goes into production after about 8 hours for a soft launch so having this issue resolved sooner rather than later would be good even if it was just removing the scroll-locking functionality completely, thanks!

**Comment by neosiae** [comment]
@jokokoloko  Until we fix this issue, you can turn off body scroll lock via props, just set `lockBodyAfterOpen` to `false`.

**Comment by neosiae** [comment]
@jokokoloko You can turn off body scroll lock via props, just set `lockBodyAfterOpen` to `false`, until we fix this issue.

**Comment by jokokoloko** [comment]
Perfect, thanks!

**Comment by neosiae** [comment]
@jokokoloko Please try the latest version.

**Comment by jokokoloko** [comment]
Latest version works great, thanks!

https://www.myhealthconfirm.com/
